base_link:
  sensor_kit_base_link:
    x: -0.158
    y: 0.0
    z: 1.41
    roll: 0.00
    pitch: -0.112
    yaw: 0.00

  imu:
    x: 0.39
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
